# Generated by Django 3.1.4 on 2022-01-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob_no', models.CharField(max_length=10)),
                ('speaker', models.BooleanField(default=False)),
                ('time', models.DecimalField(decimal_places=3, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mobile Setting',
                'verbose_name_plural': 'Mobile Settings',
            },
        ),
        migrations.CreateModel(
            name='VBSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DecimalField(decimal_places=3, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Voice Bot Setting',
                'verbose_name_plural': 'Voice Bot Settings',
            },
        ),
    ]
