# Generated by Django 3.1.4 on 2022-01-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_mobilesettings_vbsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilesettings',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vbsettings',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
