# Generated by Django 3.1.4 on 2022-01-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20220105_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DecimalField(decimal_places=4, max_digits=20)),
                ('bot_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Hand Setting',
                'verbose_name_plural': 'Hand Settings',
            },
        ),
        migrations.AddField(
            model_name='mobilesettings',
            name='bot_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vbsettings',
            name='bot_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
